{{ if or (index .Values "tags" "eric-pm-server") (index .Values "tags" "eric-adp-common") }}
{{- if not (index .Values "eric-pm-server" "rbac" "appMonitoring" "enabled") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "eric-adp-5g-udm.pm-server.clusterrole.name" . }}
  labels:
{{- include "eric-adp-5g-udm.labels" . | indent 4 }}
  annotations:
{{- include "eric-adp-5g-udm.product-info" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "eric-adp-5g-udm.pm-server.clusterrole.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "eric-adp-5g-udm.pm-server.serviceaccount.name" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
