{{ if or (index .Values "tags" "eric-pm-server") (index .Values "tags" "eric-adp-common") }}
{{- if not (index .Values "eric-pm-server" "rbac" "appMonitoring" "enabled") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "eric-adp-5g-udm.pm-server.serviceaccount.name" . }}
  labels:
{{- include "eric-adp-5g-udm.labels" . | indent 4 }}
  annotations:
{{- include "eric-adp-5g-udm.product-info" . | indent 4 }}
{{- end }}
{{- end }}
