{{ if or (index .Values "tags" "eric-tm-ingress-controller-cr") (index .Values "tags" "eric-adp-common") }}
{{ if and (index .Values "tags" "eric-sec-certm") (.Values.global.createExternalCertificateCR) }}
apiVersion: certm.sec.ericsson.com/v1
kind: ExternalCertificate
metadata:
  name: {{ default (printf "%s-iccr-external-cert" (include "eric-adp-5g-udm.name" .)) }}
  labels:
{{- include "eric-adp-5g-udm.labels" . | indent 4 }}
  annotations:
{{- include "eric-adp-5g-udm.product-info" . | indent 4 }}
spec:
  generated-secret-name: {{ index .Values "eric-tm-ingress-controller-cr" "tlsSecret" }}
  generated-secret-type: tls
  asymmetric-key-certificate-name: {{ index .Values "eric-tm-ingress-controller-cr" "externalCertificate" "keyAndCertificateName" }}
{{- end }}
{{- end }}
