apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eric-log4shell-patch.name" . }}
data:
  ccxx-components.sh: |-
   #!/bin/bash
   
   export CCXX_MICROS=(
   {{- range .Values.log4shell.ccxxmicros }}
     {{ . | quote}} \
   {{- end }}
   )

  adp-components.sh: |-
   #!/bin/bash
   
   export ADP_MICROS=(
   {{- range .Values.log4shell.adpmicros }}
     {{ . | quote }} \
   {{- end }}
   )

  set-env.sh: |-
   #!/bin/bash
   
   export ENV_VARIABLES=(
   {{- range .Values.log4shell.envVariable }}
     {{ .element | quote }} \
     {{ .name | quote }} \
     {{ .value | quote }} \
   {{- end }}
   )

